gradle enterprise
micronaut-projects/micronaut-starter pull request #1047
Opened 2022-01-27 12:02 UTC by sdelamo

This add support for adding the Gradle Enterprise plugin. Useful, if you want to use starter-core in your company and generate all your apps pushing to a particular server.

2022-01-27 12:05 UTC, sdelamo commented
@alextu It would be great to support this for maven as well. Not sure if you can help with it.

2022-01-27 12:32 UTC, timyates requested changes

2022-01-27 12:32 UTC, timyates commented on starter-core/src/main/java/io/micronaut/starter/feature/build/gradle/templates/settingsGradle.rocker.raw
> +if (gradleBuild.getDsl() == GradleDsl.KOTLIN) {
should be `@if (gradleBuild.getDsl() == GradleDsl.KOTLIN)` (missing `@`)

2022-01-27 12:39 UTC, timyates requested changes

2022-01-27 12:39 UTC, timyates commented on starter-core/src/main/java/io/micronaut/starter/feature/build/gradle/templates/settingsGradle.rocker.raw
> +
NIT: Another CRLF here makes the file look nicer

2022-01-27 12:43 UTC, timyates commented on starter-core/src/main/java/io/micronaut/starter/feature/build/gradle/templates/settingsGradle.rocker.raw
> +if (gradleBuild.getDsl() == GradleDsl.KOTLIN) {
fix pushed

2022-01-27 12:44 UTC, timyates approved these changes

2022-01-28 09:07 UTC, alextu commented
> @alextu It would be great to support this for maven as well. Not sure if you can help with it.

Thanks for tagging me, I'll check if it's something we can take

2022-03-02 10:03 UTC, etiennestuder requested changes
@sdelamo It is of course your call, but if you could address the feedback I left re: TOS in the settings.gradle, that would be great.

2022-03-02 10:03 UTC, etiennestuder commented on starter-core/src/test/groovy/io/micronaut/starter/feature/build/gradle/MicronautGradleEnterpriseSpec.groovy
> +        if (buildTool == BuildTool.GRADLE_KOTLIN) {
TOS agreement is only needed when publishing to scans.gradle.com. When configuring a GE server via `server = `, there is no need to accept the TOS since the customer running that instance has already agreed to the TOS separately.

2022-03-17 11:12 UTC, sdelamo commented on starter-core/src/test/groovy/io/micronaut/starter/feature/build/gradle/MicronautGradleEnterpriseSpec.groovy
> +        if (buildTool == BuildTool.GRADLE_KOTLIN) {
I have done the change.

2022-03-19 09:40 UTC, merged