Switch from jackson-databind to micronaut-serde-jackson
micronaut-projects/micronaut-starter pull request #1060
Opened 2022-02-02 14:00 UTC by n0tl3ss

Switching from jackson-databind to micronaut-serde-jackson should give the application better performance.

2022-02-03 18:55 UTC, jameskleeh approved these changes

2022-02-04 08:59 UTC, graemerocher approved these changes

2022-02-05 06:52 UTC, sdelamo requested changes

2022-02-05 06:52 UTC, sdelamo commented on starter-analytics-postgres/build.gradle
> +                .using(module("io.micronaut.serde:micronaut-serde-jackson:1.0.0-M6"))
I think the version number should be in `gradle.properties`

2022-02-05 06:52 UTC, sdelamo commented on starter-cli/build.gradle
> +                .using(module("io.micronaut.serde:micronaut-serde-jackson:1.0.0-M6"))
I think the version number should be in `gradle.properties`

2022-02-05 06:52 UTC, sdelamo commented on starter-core/build.gradle
> +                .using(module("io.micronaut.serde:micronaut-serde-jackson:1.0.0-M6"))
I think the version number should be in `gradle.properties`

2022-02-05 06:52 UTC, sdelamo commented on starter-analytics-postgres/src/main/java/io/micronaut/starter/analytics/postgres/TotalDTO.java
>  public class TotalDTO {
Add a test https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29

2022-02-05 06:52 UTC, sdelamo commented on starter-api/src/main/java/io/micronaut/starter/api/ApplicationTypeDTO.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-api/src/main/java/io/micronaut/starter/api/ApplicationTypeDTO.java
> +                       @Nullable List<FeatureDTO> features) {
why did you needed to make it `@Nullable`?

2022-02-05 06:52 UTC, sdelamo commented on starter-api/src/main/java/io/micronaut/starter/api/ApplicationTypeList.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-api/src/main/java/io/micronaut/starter/api/BuildToolDTO.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-api/src/main/java/io/micronaut/starter/api/FeatureDTO.java
>  @Schema(name = "Feature")
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-api/src/main/java/io/micronaut/starter/api/FeatureList.java
>  public class FeatureList extends Linkable {
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-api/src/main/java/io/micronaut/starter/api/JdkVersionDTO.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-api/src/main/java/io/micronaut/starter/api/LanguageDTO.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-api/src/main/java/io/micronaut/starter/api/LinkDTO.java
>  public class LinkDTO {
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-api/src/main/java/io/micronaut/starter/api/Linkable.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-api/src/main/java/io/micronaut/starter/api/SelectOptionDTO.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-api/src/main/java/io/micronaut/starter/api/SelectOptionsDTO.java
>  public class SelectOptionsDTO {
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-api/src/main/java/io/micronaut/starter/api/TestFrameworkDTO.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-api/src/main/java/io/micronaut/starter/api/TestFrameworkDTO.java
> +    TestFrameworkDTO(TestFramework value, String name, String description, @Nullable LanguageDTO defaultLanguage, @Nullable List<LanguageDTO> supportedLanguages) {
why did need to make these `@Nullable`?

2022-02-05 06:52 UTC, sdelamo commented on starter-api/src/main/java/io/micronaut/starter/api/VersionDTO.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-api/src/main/java/io/micronaut/starter/api/create/github/GitHubCreateDTO.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-api/src/main/java/io/micronaut/starter/api/options/ApplicationTypeSelectOptions.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-api/src/main/java/io/micronaut/starter/api/options/BuildToolSelectOptions.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-api/src/main/java/io/micronaut/starter/api/options/JdkVersionSelectOptions.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-api/src/main/java/io/micronaut/starter/api/options/LanguageSelectOptions.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-api/src/main/java/io/micronaut/starter/api/options/TestFrameworkSelectOptions.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-api/src/main/java/io/micronaut/starter/api/preview/PreviewDTO.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-cli/src/main/java/io/micronaut/starter/cli/CodeGenConfig.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-cli/src/main/java/io/micronaut/starter/cli/command/BuildToolConverter.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/analytics/Generated.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/analytics/SelectedFeature.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/build/dependencies/Coordinate.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/build/dependencies/DependencyCoordinate.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/client/github/oauth/AccessToken.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/client/github/v3/GitHubRepository.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/client/github/v3/GitHubSecret.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/client/github/v3/GitHubSecretsPublicKey.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/client/github/v3/GitHubUser.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/client/github/v3/GitHubWorkflowRun.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/client/github/v3/GitHubWorkflowRuns.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/defaults/LanguageDefaults.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-05 06:52 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/function/DocumentationLink.java
> +@Serdeable
Please, add a [test](https://github.com/micronaut-advocacy/micronaut-live-newsletter/blob/7b42a0835ed800e4aef1133ce1c77f15a5829053/app/src/test/groovy/com/objectcomputing/newsletter/live/SubscriberSpec.groovy#L20-L29)

2022-02-07 18:43 UTC, n0tl3ss commented on starter-api/src/main/java/io/micronaut/starter/api/ApplicationTypeDTO.java
> +                       @Nullable List<FeatureDTO> features) {
this has to stay because test "test application types" from ApplicationControllerSpec keeps failing without it.

2022-02-07 21:18 UTC, sdelamo requested changes

2022-02-07 21:18 UTC, sdelamo commented on starter-api/src/test/groovy/io/micronaut/starter/api/SerdeSpec.groovy
> +    void "#type is annotated with @Serdeable.Deserializable"(Type type) {
Please, annotate with `@Unroll`

2022-06-21 12:25 UTC, closed without merging