Issue 1285 - add feature for `micronaut-test-rest-assured` module of Micronaut Test
micronaut-projects/micronaut-starter pull request #1288
Opened 2022-06-08 21:30 UTC by wetted

closes #1285

2022-06-08 21:39 UTC, wetted commented
The feature validation I implemented allows any language and only JUnit5 test framework. Does that make sense? Should we omit Groovy language, include KoTest? Let me kno what you think and I'll make the changes if necessary.

2022-06-09 09:27 UTC, sdelamo requested changes

2022-06-09 09:27 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/test/MicronautRestAssured.java
> +        return "Micronaut-Test Rest-Assured";
Replace `Rest-Assured` with `REST-assured`. That it is how they write it. see: https://rest-assured.io

2022-06-09 09:27 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/test/MicronautRestAssuredValidator.java
> +public class MicronautRestAssuredValidator implements FeatureValidator {
remove `MicronautRestAssuredValidator`. 

You can use `micronaut-test-rest-assured` with Spock and KoTest. 

> You can then inject instances of [RequestSpecification](https://www.javadoc.io/static/io.rest-assured/rest-assured/5.1.0/io/restassured/specification/RequestSpecification.html) into test fields or method parameters 
(parameters are only supported with JUnit 5):

Based on the docs, I think you should be able to do: 

```groovy
@MicronautTest 
public class RestAssuredHelloWorldSpec extends Specification {
    @Inject  
   RequestSpecification requestSpec
   void "test hello world"() {
```

2022-06-09 09:27 UTC, sdelamo commented on starter-core/src/test/groovy/io/micronaut/starter/feature/test/MicronautRestAssuredSpec.groovy
> +    void 'test gradle micronaut-test-rest-assured feature fails for language=#language when test framework is not Junit'() {
other test frameworks appart from Junit should be supported

2022-06-10 07:58 UTC, sdelamo approved these changes

2022-06-17 07:29 UTC, merged