Add feature which generates Google Cloud Build Configuration file
micronaut-projects/micronaut-starter pull request #1298
Opened 2022-06-20 17:19 UTC by wetted

closes #1281

2022-06-20 17:23 UTC, wetted commented
I am having some Docker issues smoke testing gradle/maven projects using `cloud-build-local`, but I can't successfully run `./gradlew dockerBuild` either, and it looks like a problem with me running on Apple silicon. I'm investigating, but I believe the code for this feature is correct.

2022-06-21 06:53 UTC, sdelamo requested changes

2022-06-21 06:53 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/ci/workflows/gcp/templates/cloudBuild.rocker.raw
> +  - name: gcr.io/cloud-builders/docker
I recommend removing the step to containerize our application. 

Moreover, I think our recommended approach is to containerize the application using Gradle is to use the [Micronaut Gradle Plugin docker related tasks](https://micronaut-projects.github.io/micronaut-gradle-plugin/latest/#_docker_support)

2022-06-21 06:53 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/ci/workflows/gcp/templates/cloudBuild.rocker.raw
> +  - name: gcr.io/cloud-builders/docker
I recommend removing the step to containerize our application. 

Moreover, I think our recommended approach is to containerize the application using Maven is to use the [Micronaut Maven Plugin Docker packaging options](https://micronaut-projects.github.io/micronaut-maven-plugin/latest/examples/package.html#building_jvm_based_docker_images)

2022-06-21 06:54 UTC, sdelamo requested changes

2022-06-21 06:54 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/ci/workflows/gcp/templates/cloudBuild.rocker.raw
> +    args: ["assemble"]
I think we should have a single step which runs the `build` task.

2022-07-05 11:43 UTC, sdelamo commented
@wetted is this ready for review or should be in Draft still?

2022-07-05 13:49 UTC, merged