Add Oracle Cloud DevOps CI Workflow
micronaut-projects/micronaut-starter pull request #1302
Opened 2022-06-24 14:41 UTC by n0tl3ss

This PR adds `Oracle Cloud DevOps Build CI Workflow` feature. 

- It adds `build_spec.yml` into the root of the generated project that is required for the Oracle Cloud DevOps Build tool.
- Adds test that verify generated file

Docs that are related: 
- https://docs.oracle.com/en-us/iaas/Content/devops/using/build_specs.htm - file format specification
- https://docs.oracle.com/en-us/iaas/Content/devops/using/devops_iampolicies.htm - how to setup CI

2022-06-24 15:55 UTC, alvarosanchez approved these changes

2022-06-24 16:19 UTC, wetted approved these changes

2022-06-24 16:33 UTC, graemerocher commented
Needs a few improvements:

1. if the GraalVM feature is selected we should build a native image
2. We need a way to generate a build that builds docker images (both native and not native) since the output artefact can be a `DOCKER_IMAGE`. See https://docs.oracle.com/en-us/iaas/Content/devops/using/build_specs.htm

2022-06-27 17:17 UTC, graemerocher approved these changes

2022-06-27 19:52 UTC, wetted commented on starter-core/src/main/java/io/micronaut/starter/feature/ci/workflows/oci/OCICiWorkflowFeature.java
> +    private static final String GRAALVM_VERSION = "22.1.0";
```suggestion
```

2022-06-27 19:52 UTC, wetted commented on starter-core/src/main/java/io/micronaut/starter/feature/ci/workflows/oci/OCICiWorkflowFeature.java
> +                    GRAALVM_VERSION
```suggestion
                    VersionInfo.getDependencyVersion("graal")
```

2022-06-27 19:53 UTC, wetted requested changes
Avoid hard coding versions. Use `VersionInfo` API whenever possible

2022-06-27 21:02 UTC, wetted approved these changes

2022-07-05 15:31 UTC, merged