Hibernate reactive 11
micronaut-projects/micronaut-starter pull request #1318
Opened 2022-07-06 16:35 UTC by timyates

Closes #1317

2022-07-07 06:34 UTC, sdelamo requested changes

2022-07-07 06:34 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/database/HibernateReactiveFeatureValidator.java
> +            System.out.println(options.getJavaVersion().majorVersion());
remove println statement

2022-07-07 06:34 UTC, sdelamo commented on starter-core/src/test/groovy/io/micronaut/starter/feature/database/DataHibernateReactiveSpec.groovy
> +        def ex = thrown(IllegalArgumentException)
Much nicer: 

`IllegalArgumentException ex = thrown()`

than: 

`def ex = thrown(IllegalArgumentException)`

2022-07-07 06:34 UTC, sdelamo commented on starter-core/src/test/groovy/io/micronaut/starter/feature/database/HibernateReactiveJpaSpec.groovy
> +        def ex = thrown(IllegalArgumentException)
Much nicer: 

`IllegalArgumentException ex = thrown()`
        
than: 

`def ex = thrown(IllegalArgumentException)`

2022-07-07 06:38 UTC, sdelamo commented
I think you have to annotate `DataHibernateReactiveSpec` and `HibernateReactiveJpaSpec` with `@IgnoreIf({ jvm.java8 })`

2022-07-07 08:40 UTC, timyates commented
> I think you have to annotate `DataHibernateReactiveSpec` and `HibernateReactiveJpaSpec` with `@IgnoreIf({ jvm.java8 })`

Gah, I had this previously, but it passed locally without it on java 8, so I dropped it...

Added back in 👍

2022-07-07 13:04 UTC, timyates commented
@sdelamo Any ideas on the failure?  The AmazonCorreto spec is failing

https://ge.micronaut.io/s/zpd3htqttl3xa/tests/overview?outcome=failed

And seems to be failing quite a lot today

https://ge.micronaut.io/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Failed%20to%20execute%20goal%20org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile%20(default-compile)%20on%20project%20foo:%20Fatal%20error%20compiling&search.timeZoneId=Europe/London

2022-07-08 14:29 UTC, sdelamo commented
> @sdelamo Any ideas on the failure? The AmazonCorreto spec is failing
> 
> https://ge.micronaut.io/s/zpd3htqttl3xa/tests/overview?outcome=failed
> 
> And seems to be failing quite a lot today
> 
> https://ge.micronaut.io/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Failed%20to%20execute%20goal%20org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile%20(default-compile)%20on%20project%20foo:%20Fatal%20error%20compiling&search.timeZoneId=Europe/London

Restarted the build and it passed 🤷

2022-07-08 14:29 UTC, sdelamo approved these changes

2022-07-08 14:30 UTC, merged