Add feature for google cloudevents function
micronaut-projects/micronaut-starter pull request #1550
Opened 2022-11-24 17:07 UTC by guillermocalvo

2022-11-24 17:12 UTC, sdelamo requested changes
Please add a functional tests which generates projects and verify they compile

2022-11-24 17:20 UTC, sdelamo requested changes

2022-11-24 17:20 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/function/gcp/GoogleCloudEventsFunction.java
> +        if (type == ApplicationType.FUNCTION) {
this should not be necessary since this feature should only be applicable if ApplicationType.FUNCTION

2022-11-24 17:20 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/function/gcp/GoogleCloudEventsFunction.java
> +            switch (language) {
extract a method

```
RockerModel sourceFileModel(GeneratorContext generatorContext) {
 Language language = generatorContext.getLanguage();
             Project project = generatorContext.getProject();
          switch (language) {
                 case GROOVY:
return new RockerTemplate(
                         sourceFile,
                         gcpCloudEventsFunctionGroovy.template(project)));
                     break;
                 case KOTLIN:
return                      new RockerTemplate(
                         sourceFile,
                         gcpCloudEventsFunctionKotlin.template(project)));
                     break;
                 case JAVA:
                 default:
           return           new RockerTemplate(
                         sourceFile,
                         gcpCloudEventsFunctionJava.template(project)));
             }
}
```

2022-11-24 17:20 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/function/gcp/GoogleCloudEventsFunction.java
> +    public void processSelectedFeatures(FeatureContext featureContext) {
remove method

2022-11-24 17:20 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/function/gcp/GoogleCloudEventsFunction.java
> +    protected void applyTestTemplate(GeneratorContext generatorContext, Project project, String name) {
remove method

2022-11-24 17:20 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/function/gcp/GoogleCloudEventsFunction.java
> +public class GoogleCloudEventsFunction extends AbstractGoogleCloudFunction {
overrides `supports(ApplicationType)` method and return false unless `ApplicationType.FUNCTION`

2022-11-24 17:20 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/function/gcp/template/cloudevents/gcpCloudEventsFunctionKotlin.rocker.raw
> +        BackgroundFunction<PubSubMessage> {
this is incorrect it is not a `BackgroundFunction`

2022-11-24 17:20 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/function/gcp/GoogleCloudFunctionFeatureValidator.java
> +        if (features.stream().anyMatch(f -> f instanceof GoogleCloudFunction || f instanceof GoogleCloudRawFunction || f instanceof GoogleCloudEventsFunction)) {
are not these three classes extensions of `AbstractGoogleCloudFunction` Could you use that instead?

2022-11-28 10:52 UTC, guillermocalvo commented
> Please add a functional tests which generates projects and verify they compile

@sdelamo Thanks for your feedback! I pushed some fixes and added functional tests to subproject `test-cloud`.

2023-01-11 05:32 UTC, sdelamo commented
@guillermocalvo can you change the base branch of this PR to 3.9.x 

Moreover, resolved the conversations you have addressed by clicking the "Resolve Conversation" button. 

Thanks!

2023-01-11 05:32 UTC, sdelamo requested changes
change the pr base

2023-01-16 16:56 UTC, sdelamo requested changes
Please add a unit test for the feature. 

See: https://github.com/micronaut-projects/micronaut-starter/pull/1590

2023-02-06 12:22 UTC, sdelamo requested changes

2023-02-06 12:22 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/function/gcp/GoogleCloudEventsFunction.java
> +        generatorContext.addDependency(Dependency.builder()
use `MicronautDependencyUtils`

2023-02-06 12:22 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/function/gcp/GoogleCloudEventsFunction.java
> +        generatorContext.addDependency(Dependency.builder()
`MicronautDependencyUtils::serdeDependency`

2023-02-06 12:22 UTC, sdelamo commented on starter-core/src/test/groovy/io/micronaut/starter/feature/function/gcp/GoogleCloudEventsFunctionSpec.groovy
> +        build.contains('implementation("io.micronaut.gcp:micronaut-gcp-function-cloudevents")')
Use `BuildTestVerifier` API https://github.com/micronaut-projects/micronaut-starter/pull/1590

2023-02-23 06:18 UTC, sdelamo requested changes

2023-02-23 06:18 UTC, sdelamo commented on test-cloud/src/test/groovy/io/micronaut/starter/core/test/cloud/gcp/CreateGoogleCloudFunctionCloudEventsSpec.groovy
> +@Retry // can fail on CI due to port binding race condition, so retry
```suggestion
```

2023-02-23 06:18 UTC, sdelamo commented on starter-core/src/test/groovy/io/micronaut/starter/feature/function/gcp/GoogleCloudEventsFunctionSpec.groovy
> +        buildTool << [BuildTool.GRADLE, BuildTool.MAVEN]
```suggestion
        buildTool << BuildTool.values()
```

2023-02-23 06:18 UTC, sdelamo commented on starter-core/src/test/groovy/io/micronaut/starter/feature/function/gcp/GoogleCloudEventsFunctionSpec.groovy
> +        buildTool << [BuildTool.GRADLE, BuildTool.MAVEN]
```suggestion
        buildTool << BuildTool.values()
```

2023-02-23 06:35 UTC, sdelamo approved these changes

2023-03-10 07:31 UTC, sdelamo approved these changes

2023-03-10 07:31 UTC, merged