Add feature for Micronaut AWS APIGateway (dependency and docs links)
micronaut-projects/micronaut-starter pull request #1559
Opened 2022-11-29 18:21 UTC by wetted

closes #1549

2022-12-08 17:43 UTC, sdelamo requested changes
Can you create a OneOfFeature for AmzonAPIGateway. Both `AmazonApiGateway` and `AmazonApiGatewayHttp` should extend this new class.

2022-12-08 17:43 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/aws/Cdk.java
> +            dependencyContext.addDependency(MicronautDependencyUtils.awsDependency()
we don't need this

2022-12-08 17:43 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/aws/Cdk.java
> +        if (generatorContext.getFeatures().hasFeature(AmazonApiGateway.class)) {
we don't need this

2022-12-08 17:43 UTC, sdelamo commented on starter-core/src/test/groovy/io/micronaut/starter/feature/aws/AmazonApiGatewaySpec.groovy
> +        output."$Cdk.INFRA_MODULE/build.gradle".contains($/implementation("io.micronaut.aws:micronaut-aws-apigateway/$)
we don't need this

2022-12-08 17:43 UTC, sdelamo commented on starter-core/src/test/groovy/io/micronaut/starter/feature/aws/AmazonApiGatewaySpec.groovy
> +        output."build.gradle".contains($/implementation("io.micronaut.aws:micronaut-aws-apigateway/$)
we don't need this

2022-12-08 19:39 UTC, wetted commented
> Can you create a OneOfFeature for AmzonAPIGateway. Both `AmazonApiGateway` and `AmazonApiGatewayHttp` should extend this new class.

It already is and there is a test for that in `AmazonApiGatewayHttpSpec`

2022-12-09 14:14 UTC, wetted commented on starter-core/src/main/java/io/micronaut/starter/feature/aws/Cdk.java
> +            dependencyContext.addDependency(MicronautDependencyUtils.awsDependency()
removed

2022-12-09 14:14 UTC, wetted commented on starter-core/src/main/java/io/micronaut/starter/feature/aws/Cdk.java
> +        if (generatorContext.getFeatures().hasFeature(AmazonApiGateway.class)) {
removed

2022-12-09 14:14 UTC, wetted commented on starter-core/src/test/groovy/io/micronaut/starter/feature/aws/AmazonApiGatewaySpec.groovy
> +        output."build.gradle".contains($/implementation("io.micronaut.aws:micronaut-aws-apigateway/$)
removed

2022-12-09 14:14 UTC, wetted commented on starter-core/src/test/groovy/io/micronaut/starter/feature/aws/AmazonApiGatewaySpec.groovy
> +        output."$Cdk.INFRA_MODULE/build.gradle".contains($/implementation("io.micronaut.aws:micronaut-aws-apigateway/$)
removed

2022-12-09 16:18 UTC, sdelamo requested changes

2022-12-09 16:18 UTC, sdelamo commented on starter-core/src/test/groovy/io/micronaut/starter/feature/aws/AmazonApiGatewaySpec.groovy
> +    void 'amazon-api-gateway feature with Cdk has dependency in infra and doc links'() {
test description is incorrect

2022-12-09 16:18 UTC, sdelamo commented on starter-core/src/test/groovy/io/micronaut/starter/feature/aws/AmazonApiGatewaySpec.groovy
> +    void 'amazon-api-gateway feature without Cdk has dependency in project and doc links'() {
test description is incorrect

2022-12-09 16:30 UTC, sdelamo approved these changes

2022-12-19 19:44 UTC, merged