Fix log4j2 feature generating incorrect log4j2 dependencies
micronaut-projects/micronaut-starter pull request #1583
Opened 2023-01-11 22:20 UTC by wetted

closes #1560

2023-01-13 14:11 UTC, sdelamo requested changes
This is a bug fix. right? Can you change the base to 3.8.x

2023-01-13 14:11 UTC, sdelamo commented on starter-core/src/test/groovy/io/micronaut/starter/feature/logging/Log4j2Spec.groovy
> +        template.contains('implementation platform("org.apache.logging.log4j:log4j-bom:')
Please, use `BuildTestVerifier`API

2023-01-13 14:11 UTC, sdelamo commented on starter-core/src/test/groovy/io/micronaut/starter/feature/logging/Log4j2Spec.groovy
>      void "org.apache.logging.log4j dependencies are present for log4j2 feature and build maven"() {
can you use the maven in the previous test as well and get rid of this test?

2023-01-16 16:57 UTC, sdelamo approved these changes

2023-02-17 11:51 UTC, timyates approved these changes

2023-03-13 16:44 UTC, merged