Expand support of Azure functions to include jdk 17
micronaut-projects/micronaut-starter pull request #1632
Opened 2023-02-27 18:14 UTC by wetted

(currently limited to 8 and 11)

fixes #1629

2023-02-27 18:16 UTC, wetted commented
I have an interesting Spock test problem. I added JDK_17 as a supported JDK for Azure Function feature. That means it supports all the JDKs (values()) of the `JdkVersion` enum now. The `AzureCloudFunctionSpec` verifies that unsupported JDK versions raise an exception. The problem is that it now supports all of them in the enum, and the test doesn't execute since it's data driven and no longer has any data (i.e. unsupported JDK).

My first thought was to make it `@PendingFeature` with a reason that it needs a unsupported JDK in the enum. But that doesn't work because PendingFeature says, "if every iteration of a data-driven test passes it will be reported as error". I can't use `groovy.test.NotYetImplemented` or the deprecated `groovy.transform.NotYetImplemented` for similar reasons. I also don't want to add to `JdkVersion` – e.g. JDK_19 – just to make a test work. That should be under it's unique PR if we want to do that anyway, IMO.

See: https://github.com/micronaut-projects/micronaut-starter/blob/f51cf6ff43ea7eca0aacbd8e7b2ff5ab8059f8be/starter-core/src/test/groovy/io/micronaut/starter/feature/function/azure/AzureCloudFunctionSpec.groovy#L27

2023-02-27 20:08 UTC, sdelamo requested changes

2023-02-27 20:08 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/function/azure/AzureFeatureValidator.java
> +            switch (options.getJavaVersion()) {
remove

2023-02-27 20:08 UTC, sdelamo commented on starter-core/src/test/groovy/io/micronaut/starter/feature/function/azure/AzureCloudFunctionSpec.groovy
>                  ((JdkVersion.values() as List<JdkVersion>) - AzureFeatureValidatorSpec.supportedVersionsByAzureFunction()) as List<JdkVersion>,
replace with `JdkVersion.values()` and test for `noExceptionThrown()`

2023-02-27 20:08 UTC, sdelamo commented on starter-core/src/test/groovy/io/micronaut/starter/feature/function/azure/AzureFeatureValidatorSpec.groovy
>      static List<JdkVersion> supportedVersionsByAzureFunction() {
delete

2023-02-27 20:08 UTC, sdelamo requested changes

2023-02-27 20:08 UTC, sdelamo commented on starter-core/src/test/groovy/io/micronaut/starter/feature/function/azure/AzureCloudFunctionSpec.groovy
> +    // PendingFeature doesn't work here, because "if every iteration of a data-driven test passes it will be reported as error"
delete comment and `@PendingFeature`

2023-02-28 06:42 UTC, sdelamo commented
@wetted please, remember to place the PRs you want reviewed in in ready for review.

2023-02-28 06:42 UTC, merged

2023-02-28 13:43 UTC, wetted commented
> @wetted please, remember to place the PRs you want reviewed in in ready for review.

Sorry, that was an oversight. I usually do that.