Refactor rocker dependencies into java Feature API (partial)
micronaut-projects/micronaut-starter pull request #1707
Opened 2023-04-13 20:54 UTC by wetted

On Issue #1698 @sdelamo says, "we should move the logic of adding the dependencies outside of rocker into Java classes."

This implements a large portion of that. What's still left is somewhat more complicated – with conditional logic between features, inconsistencies between gradle and maven, and for other reasons – but there's no reason that should hold this part up.

The dependency logic for the azure features is broken for gradle. That's a bug so I will fix that separately.

2023-04-14 09:25 UTC, sdelamo commented
@wetted is this ready for review? it is still in draft

2023-04-14 14:13 UTC, wetted commented
> @wetted is this ready for review? it is still in draft

@sdelamo no, the unit tests pass, but something is broken in the functional/integration tests I need to address.

2023-04-14 19:10 UTC, wetted commented
I am working the Azure, GCP, and OracleCloud Rocker template refactors in separate PRs. They are somewhat more complicated, and have bugs for Gradle projects.

2023-04-15 21:13 UTC, wetted commented
> @wetted is this ready for review? it is still in draft

@sdelamo this is good to go now.

2023-04-17 09:49 UTC, alvarosanchez requested changes

2023-04-17 09:49 UTC, alvarosanchez commented on starter-core/src/main/java/io/micronaut/starter/feature/function/awslambda/AwsLambda.java
> +        }
Would it make sense to move this to the parent `AwsCloudFeature`?

2023-04-17 09:49 UTC, alvarosanchez commented on starter-core/src/main/java/io/micronaut/starter/feature/function/gcp/GoogleCloudFunction.java
> +    }
Is this needed?

2023-04-17 09:49 UTC, alvarosanchez commented on starter-core/src/main/java/io/micronaut/starter/feature/other/OpenApi.java
> +                    .versionProperty("micronaut.openapi.version")
This is probably in the BOM, so the version should be needed

2023-04-17 15:33 UTC, wetted commented on starter-core/src/main/java/io/micronaut/starter/feature/function/awslambda/AwsLambda.java
> +        }
@alvarosanchez I don't think we want to put it there. `AwsCloudFeature` is an interface that extends `CloudFeature` and not `Feature`. What I have now still matches the logic that was in the Rocker template.

2023-04-17 17:57 UTC, wetted commented
@alvarosanchez @sdelamo 

I added another change set that refactors the GCP dependencies from rocker files into the Feature classes. Please review that as well.

2023-04-18 07:12 UTC, alvarosanchez approved these changes

2023-04-18 15:19 UTC, alvarosanchez approved these changes

2023-04-19 19:47 UTC, wetted commented
I am now able to duplicate the failing test locally. I am working on fixing it.

2023-04-20 12:26 UTC, merged