Fixing missing dependencies for Gradle projects with "azure-function-http" feature
micronaut-projects/micronaut-starter pull request #1708
Opened 2023-04-14 14:26 UTC by wetted

Fixing missing dependencies for Gradle projects with "azure-function-http" feature, to make constant with Maven projects. Refactor dependency logic from Rocker files to Feature classes.

2023-04-15 17:21 UTC, wetted commented
@sdelamo if #1709 is merged first – has a bugfix I need – I can add a minor improvement to `AzureHttpFunctionSpec`.

2023-04-17 09:50 UTC, alvarosanchez approved these changes

2023-04-17 10:10 UTC, sdelamo requested changes
> Fixing missing dependencies for Gradle projects with "azure-function-http" feature, to make that consistent with Maven projects. Refactor dependency logic from Rocker files to Feature classes.

It is not a bug in gradle. The [gradle plugin adds those dependencies automatically.](https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/3.7.x/minimal-plugin/src/main/java/io/micronaut/gradle/MicronautRuntimeDependencies.java).

2023-04-17 11:15 UTC, sdelamo requested changes

2023-04-17 11:15 UTC, sdelamo commented on starter-core/src/test/groovy/io/micronaut/starter/feature/function/azure/AzureHttpFunctionSpec.groovy
> +                .features(['azure-function-http'])
azure-function-http is invisible. We should test `azure-function` and `ApplicationType.DEFAULT` and  `azure-function` and `ApplicationType.FUNCTION`

2023-04-17 11:36 UTC, sdelamo approved these changes

2023-04-17 11:36 UTC, merged