Add default class for Micronaut Validation
micronaut-projects/micronaut-starter pull request #1717
Opened 2023-04-17 20:21 UTC by wetted

This PR has two motivations:

1. remove static dependency notation from Gradle and Maven Rocker template. See #1707
2. prepare for Micronaut 4, where the dependency notation changes, and Micronaut Validation is in it's own module with changed dependencies, and documentation we can link in the readme for generated projects. See #1698

2023-04-17 21:05 UTC, wetted commented
Moving this to draft for now. I think I'll have some more commits to add.

2023-04-18 09:49 UTC, graemerocher commented
does it need to be a default feature in 4.x?

2023-04-18 12:59 UTC, sdelamo commented
> does it need to be a default feature in 4.x?

I don't think so. I think we should keep the number of default features to a minimum

2023-04-19 12:59 UTC, sdelamo requested changes

2023-04-19 12:59 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/validator/HibernateValidationFeature.java
> -public class HibernateValidator implements Feature {
Please, don't rename the feature. We are trying to avoid unnecessary breaking changes if possible.

2023-04-19 13:27 UTC, burtbeckwith commented on starter-core/src/main/java/io/micronaut/starter/feature/validator/MicronautValidationFeature.java
> +    public String getCategory() {
this isn't needed - it's the same value as in the interface

2023-04-20 04:32 UTC, sdelamo requested changes

2023-04-20 04:32 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/validator/HibernateValidationFeature.java
> +package io.micronaut.starter.feature.validator;
dont change the package.

2023-04-20 04:32 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/validator/HibernateValidator.java
> +package io.micronaut.starter.feature.validator;
dont change the package

2023-04-20 10:02 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/validator/HibernateValidator.java
> +package io.micronaut.starter.feature.validator;
resolved via https://github.com/micronaut-projects/micronaut-starter/pull/1717/commits/52687ebdd4cf8c507d807c2d7e4d74ff1124088d

2023-04-20 10:02 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/validator/HibernateValidationFeature.java
> +package io.micronaut.starter.feature.validator;
resolved via https://github.com/micronaut-projects/micronaut-starter/pull/1717/commits/52687ebdd4cf8c507d807c2d7e4d74ff1124088d

2023-04-20 10:03 UTC, sdelamo approved these changes

2023-04-20 12:28 UTC, sdelamo approved these changes

2023-04-20 12:28 UTC, merged