Add testcontainers kafka dependency to kafka+testcontainers features.
micronaut-projects/micronaut-starter pull request #2005
Opened 2023-08-08 19:02 UTC by wetted

closes #2000

2023-08-09 08:44 UTC, timyates approved these changes

2023-08-16 07:34 UTC, sdelamo requested changes

2023-08-16 07:34 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/messaging/kafka/Kafka.java
> +        if (generatorContext.hasFeature(TestContainers.class)) {
Please, move this logic to the TestContainers feature. If Kafka feature is present add an additional dependency.

2023-08-16 16:25 UTC, sdelamo approved these changes

2023-08-16 16:25 UTC, merged