Use Micronaut OCI SDK monitoring dependency
micronaut-projects/micronaut-starter pull request #2019
Opened 2023-08-18 14:37 UTC by andriy-dmytruk

2023-08-21 06:33 UTC, sdelamo approved these changes

2023-08-21 06:33 UTC, sdelamo requested changes
It misses test

2023-08-21 08:11 UTC, yawkat approved these changes

2023-08-24 06:52 UTC, sdelamo commented
ping @andriy-dmytruk

2023-08-24 16:18 UTC, sdelamo requested changes

2023-08-24 16:18 UTC, sdelamo commented on starter-core/src/test/groovy/io/micronaut/starter/feature/micrometer/MicrometerSpec.groovy
> +        template.contains('implementation("io.micronaut.oraclecloud:micronaut-oraclecloud-bmc-monitoring")')
Please, use `BuildTestVerifier` instead to test dependency in every possible build tool.

2023-08-24 17:15 UTC, sdelamo approved these changes

2023-08-24 19:54 UTC, merged