Community feature for slf4j-simple-logger
micronaut-projects/micronaut-starter pull request #2079
Opened 2023-09-27 18:51 UTC by wetted

https://github.com/GoodforGod/slf4j-simple-logger [skip ci]

closes #1654

2023-09-28 07:44 UTC, sdelamo requested changes
Ping @GoodforGod

2023-09-28 07:44 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/logging/Slf4jSimpleLogger.java
> +            .compile()
This should be `runtimeOnly`

2023-09-29 16:32 UTC, sdelamo requested changes
Thinking about this. I think we should create a OneOf marker interface for Slf4j implementation. Users should not add this dependency and logback at the same time. They should add either this one or logback.

2023-09-29 17:25 UTC, wetted commented
> Thinking about this. I think we should create a OneOf marker interface for Slf4j implementation. Users should not add this dependency and logback at the same time. They should add either this one or logback.

@sdelamo I already changed the `Slf4jSimpleLogger` feature to be a `LoggingFeature`. I believe that satisfies what you want since the other logger features are `LoggingFeature`, and that is a `OneOfFeature`.

2023-10-02 04:24 UTC, sdelamo approved these changes

2023-10-02 04:24 UTC, sdelamo commented on starter-api/src/test/groovy/io/micronaut/starter/api/FeatureControllerSpec.groovy
> -                'camunda-zeebe',
trailing comma is also allowed in groovy lists

2023-10-02 04:24 UTC, merged