Add micronaut-openapi-adoc feature (asciidoc conversion).
micronaut-projects/micronaut-starter pull request #2219
Opened 2023-12-04 16:37 UTC by wetted

closes #2206

2023-12-04 19:09 UTC, wetted commented
broken build needs a resolution for https://github.com/micronaut-projects/micronaut-core/issues/10204

2023-12-05 09:30 UTC, sdelamo requested changes

2023-12-05 09:30 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/other/OpenApiAdoc.java
> +        generatorContext.getConfiguration().put("micronaut.openapi.adoc.enabled", true);
remove this property. The default value is `true`. Thus, we don't need to add it.

2023-12-06 16:48 UTC, sdelamo approved these changes

2023-12-06 16:48 UTC, merged