Add OpenSearch features.
micronaut-projects/micronaut-starter pull request #2421
Opened 2024-03-25 19:44 UTC by wetted

closes #2414

2024-03-27 06:20 UTC, sdelamo requested changes

2024-03-27 06:20 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/opensearch/OpenSearchFeature.java
> +        return Category.CLIENT;
category should be `SEARCH_ENGINE` instead. the same elastic search feature uses. 

https://github.com/micronaut-projects/micronaut-starter/blob/4.4.x/starter-core/src/main/java/io/micronaut/starter/feature/Category.java#L49

2024-03-27 06:20 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/opensearch/OpenSearchRestClient.java
> +    private final Dependency jacksonDatabindDependency = MicronautDependencyUtils
remove unused variable.

2024-03-27 06:20 UTC, sdelamo commented on starter-core/src/test/groovy/io/micronaut/starter/feature/opensearch/OpenSearchFeatureSpec.groovy
> +        Category.CLIENT == opensearchFeature.getCategory()
this should be SEARCH_ENGINE

2024-03-27 06:21 UTC, sdelamo requested changes
if the user selects Testcontainers. We should add https://github.com/micronaut-projects/micronaut-opensearch/blob/master/gradle/libs.versions.toml#L44 see https://github.com/micronaut-projects/micronaut-starter/pull/2413

2024-03-27 14:50 UTC, wetted commented
> if the user selects Testcontainers. We should add https://github.com/micronaut-projects/micronaut-opensearch/blob/master/gradle/libs.versions.toml#L44 see #2413

I'll wait until #2413 is merged and make this a `ContributingTestContainerArtifactId` feature.

2024-03-28 10:47 UTC, sdelamo commented
@wetted #2413 is merged.

2024-03-29 14:17 UTC, sdelamo approved these changes

2024-03-29 14:17 UTC, merged