Add missing `replaceLogbackXml` in aot build configuration for gradle and maven.
micronaut-projects/micronaut-starter pull request #2424
Opened 2024-03-27 17:01 UTC by wetted

closes #2418

2024-03-27 17:02 UTC, wetted commented
ping @sdelamo this probably needs to change base to 4.5.x branch once it's created

2024-03-28 14:16 UTC, sdelamo commented
@wetted Can you merge 4.4.x into this PR? see: https://github.com/micronaut-projects/micronaut-starter/pull/2419

2024-03-28 14:21 UTC, melix approved these changes

2024-03-28 14:21 UTC, sdelamo requested changes
Merge 4.4.x into this PR.

2024-03-28 14:21 UTC, sdelamo commented on starter-core/src/test/resources/expected-aot-native-image.properties
> +logback.xml.to.java.enabled=false
```suggestion
logback.xml.to.java.enabled=true
```

2024-03-29 14:14 UTC, sdelamo approved these changes

2024-03-29 14:15 UTC, merged