Add micronaut-json-schema feature.
micronaut-projects/micronaut-starter pull request #2432
Opened 2024-04-09 19:34 UTC by wetted

closes #2431

This needs to target 4.5.x once that branch is created

2024-04-09 21:33 UTC, wetted commented
ping @sdelamo Should this support all application types?

2024-04-10 11:06 UTC, sdelamo commented
> ping @sdelamo Should this support all application types?

Yes.

2024-04-10 11:09 UTC, sdelamo requested changes
Remove `JsonSchemaConfiguration`. I think we may change the base uri to `http.//localhost:8080/schemas`. 

Create an extra feature to add[ json-schema-validation](https://github.com/micronaut-projects/micronaut-json-schema/pull/19) module to the test class path. 

Add static-resources configuration to expose the features.

2024-04-10 16:05 UTC, wetted commented
> Create an extra feature to add[ json-schema-validation](https://github.com/micronaut-projects/micronaut-json-schema/pull/19) module to the test class path.

@sdelamo What kind of logic do you want for adding one and/or the other, or validating the presence of them?
- [ ] add `json-schema-validator` feature if not present when selecting `json-schema` feature?
- [ ] `FeatureValidator` to assert `json-schema` is present if `json-schema-validator` is selected?
- [ ]  something else?

2024-04-11 05:47 UTC, sdelamo requested changes

2024-04-11 05:47 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/json/JsonSchemaFeature.java
> +        configuration.put("micronaut.router.static-resources.jsonschema.paths", "classpath:META-INF/schemas");
Please, use `ContributingStaticResources` api.

2024-04-11 05:47 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/json/JsonSchemaValidationFeature.java
> +public class JsonSchemaValidationFeature implements Feature {
Apply JsonSchemaFeature if `json-schema-validation` is selected.

2024-04-11 05:47 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/json/JsonSchemaValidationFeatureValidator.java
> +public class JsonSchemaValidationFeatureValidator implements FeatureValidator {
delete

2024-04-11 17:39 UTC, wetted commented
This is failing because `ThymeleafSpec` generates a project with `views-fieldset-tck`, and the TCK test fails. I'll see if I can figure it out.

2024-04-12 16:29 UTC, wetted commented
ping @sdelamo I merged the `ThymeleafSpec` fix and CI is green now. This should be GTG.

2024-04-18 09:53 UTC, sdelamo commented
> ping @sdelamo I merged the `ThymeleafSpec` fix and CI is green now. This should be GTG.

Let's wait until we have a release of Micronaut JSON Schema.

2024-06-01 11:59 UTC, merged