added graalpy
micronaut-projects/micronaut-starter pull request #2531
Opened 2024-07-09 13:33 UTC by tomasstupka

2024-07-09 13:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-starter?pullRequest=2531) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-starter?pullRequest=2531) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-starter?pullRequest=2531) it.</sub>

2024-07-17 11:15 UTC, timfel commented on starter-core/src/main/java/io/micronaut/starter/feature/graallanguages/MicronautGraalPyFeature.java
> +            // XXX GP is this the right place to declare the version?
A question for @graemerocher, right?

2024-08-12 13:55 UTC, fniephaus commented on starter-core/src/main/java/io/micronaut/starter/feature/graallanguages/MicronautGraalPyFeature.java
> +        return "Provides GraalPy integration with Micronaut";
I think it'd be good if this mentions "Python", for example:
```suggestion
        return "Adds support for Python using GraalPy";
```

2024-09-04 07:28 UTC, sdelamo requested changes
@tomasstupka you have to sign the CLA.

2024-09-04 07:39 UTC, sdelamo approved these changes
I have moved it to draft until 24.1.0 is released.

2024-09-04 07:39 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/graallanguages/MicronautGraalPyFeature.java
> +        return "https://micronaut-projects.github.io/micronaut-graalpy/latest/guide/";
```suggestion
        return "https://micronaut-projects.github.io/micronaut-graal-languages/latest/guide/";
```

2024-09-26 08:21 UTC, steve-s commented
```
Error: R] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 61.30 s <<< FAILURE! -- in example.micronaut.FooTest
Error: R] example.micronaut.FooTest -- Time elapsed: 61.30 s <<< ERROR!
  io.micronaut.context.exceptions.BeanInstantiationException: 
  Bean definition [org.hibernate.SessionFactory] could not be loaded: Error instantiating bean of type  [org.hibernate.boot.SessionFactoryBuilder]
   
  Message: Test resources service wasn't able to revolve expression 'jpa.default.properties.hibernate.connection.url': java.net.http.HttpTimeoutException: request timed out
  Path Taken: SessionFactoryPerJpaConfigurationFactory.buildHibernateSessionFactoryBuilder(SessionFactoryBuilder sessionFactoryBuilder) --> SessionFactoryPerJpaConfigurationFactory.buildHibernateSessionFactoryBuilder([SessionFactoryBuilder sessionFactoryBuilder]) --> SessionFactoryPerJpaConfigurationFactory.buildHibernateSessionFactoryBuilder(Metadata metadata,[JpaConfiguration jpaConfiguration])
  	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1999)
  	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:303)
```

looks like some connectivity issue, maybe we can try restarting the job?

2024-10-03 18:43 UTC, steve-s commented
@sdelamo any thoughts on the failed job? Can you try starting the jobs again? I thought that pushing artificial change could trigger them, but it didn't.

2024-11-08 12:48 UTC, merged