Issue 453 - server mismatch
micronaut-projects/micronaut-starter pull request #596
Opened 2020-12-10 17:27 UTC by wetted

Adding validation to ensure that features dependent on a Micronaut server are not combined with 3rd party servers that can't support them.

2020-12-10 17:29 UTC, wetted commented
I did the best I could to determine which starter features are micronaut-0server dependent. I probably did not get it accurate: with some missing, and other included that shouldn't be.

Just let me know. It's pretty easy to make adjustments now.

2020-12-11 09:18 UTC, alvarosanchez approved these changes

2020-12-11 12:26 UTC, ilopmar requested changes
I think this changes are a little bit "aggressive".

I'm not sure that the following dependencies do not work with Ktor. Maybe we should test them.

```
Consul, Micrometer, Multitenancy, SecuritySession, Jaeger, Zipkin, Views
```

On the other hand I think these are ok: 

```
OpenAPI, JaxRS, Management, SpringWeb.
```

Unless we are 100% sure that they don't work with Ktor I think it should be safe to not excluding them.

2020-12-17 17:20 UTC, wetted commented
As per discussion on eng meeting, I reverted `Consul`, but added all the security modules, since they depend on `@Filter`. `Micrometer, Multitenancy, Jaeger, Zipkin, Views` also depend on it so no further changes are needed.

2020-12-18 08:58 UTC, ilopmar approved these changes

2020-12-18 11:41 UTC, merged