Added Pebble support
micronaut-projects/micronaut-starter pull request #641
Opened 2021-02-02 18:51 UTC by ecmel

2021-02-02 19:07 UTC, burtbeckwith commented on starter-core/src/main/java/io/micronaut/starter/feature/view/Pebble.java
> + * Copyright 2020 original authors
should be 2021

2021-02-02 19:59 UTC, ecmel commented on starter-core/src/main/java/io/micronaut/starter/feature/view/Pebble.java
> + * Copyright 2020 original authors
Fixed

2021-02-03 09:07 UTC, alvarosanchez requested changes
Thanks for the PR! A couple of things to be changed:

* Please remove `.project` and `.settings`, and add them to `.gitignore` to avoid being committed again.
* Apart from the feature class, you also need to change the build templates to include the dependency if the feature is selected:
  * Gradle: https://github.com/micronaut-projects/micronaut-starter/blob/2.3.x/starter-core/src/main/java/io/micronaut/starter/feature/build/gradle/templates/dependencies.rocker.raw
  * Maven: https://github.com/micronaut-projects/micronaut-starter/blob/2.3.x/starter-core/src/main/java/io/micronaut/starter/feature/build/maven/templates/pom.rocker.raw

2021-02-03 12:13 UTC, ecmel commented
@alvarosanchez Updated

2021-02-03 14:48 UTC, alvarosanchez approved these changes

2021-02-03 14:57 UTC, ilopmar requested changes
You need to add tests. Please take a look at this https://github.com/micronaut-projects/micronaut-starter/blob/5928195a1f0c6abc53766851a113be01979efa56/starter-core/src/test/groovy/io/micronaut/starter/feature/view/HandlebarsSpec.groovy for handlebars

2021-02-03 18:54 UTC, ecmel commented
@ilopmar Added test

2021-02-04 06:39 UTC, ecmel commented
Pebble tests are passing

2021-02-04 08:34 UTC, alvarosanchez commented
I reran the jobs and they are all passing now.

Thank you very much for your contribution!

2021-02-04 08:34 UTC, merged