Upgrade wrapper to Gradle 7.0 for user projects
micronaut-projects/micronaut-starter pull request #745
Opened 2021-04-22 13:03 UTC by graemerocher

2021-04-22 15:38 UTC, graemerocher commented
@ilopmar this is ready for review, the failures seem to be unrelated to this change with one of them being a port binding and another being a problem downloading the `micronaut-core-reactive` POM

2021-04-23 07:23 UTC, ilopmar requested changes

2021-04-23 07:23 UTC, ilopmar commented on starter-core/src/main/java/io/micronaut/starter/feature/Features.java
> +        return VersionInfo.toJdkVersion(javaVersion.majorVersion());
I've tried a generated Kotlin app with Java 16 and it doesn't work. It fails with

```
> Task :kaptGenerateStubsKotlin
e: Unknown JVM target version: 16
Supported versions: 1.6, 1.8, 9, 10, 11, 12, 13, 14, 15

> Task :kaptGenerateStubsKotlin FAILED

FAILURE: Build failed with an exception.
```

2021-04-23 07:23 UTC, ilopmar commented on starter-core/src/main/java/io/micronaut/starter/feature/graalvm/GraalVMFeatureValidator.java
> +                throw new IllegalArgumentException("GraalVM only supports up to JDK 16");
We still doesn't support JDK 16 for GraalVM: https://github.com/oracle/graal/issues/3310

2021-04-23 07:23 UTC, ilopmar commented on starter-core/src/main/java/io/micronaut/starter/options/JdkVersion.java
> +    JDK_16(16);
:100: :tada:

2021-04-23 07:23 UTC, ilopmar commented on starter-core/src/test/groovy/io/micronaut/starter/feature/graalvm/GraalVMSpec.groovy
> -        when:
If you rollback the change I mentioned before about not supporting Java 16 with GraalVM yet, then you need to bring this test back.

2021-04-23 10:54 UTC, ilopmar commented on starter-core/src/test/groovy/io/micronaut/starter/feature/graalvm/GraalVMSpec.groovy
> -        when:
I still see this tests removed

2021-04-23 13:13 UTC, ilopmar approved these changes

2021-04-23 18:59 UTC, merged