graalvm and aws-lambda adds aws-custom-runtime
micronaut-projects/micronaut-starter pull request #776
Opened 2021-05-09 09:03 UTC by sdelamo

2021-05-10 07:22 UTC, ilopmar requested changes

2021-05-10 07:22 UTC, ilopmar commented on starter-core/src/main/java/io/micronaut/starter/feature/function/awslambda/AwsLambda.java
> +        if (featureContext.isPresent(GraalVM.class)) {
Why doing this? Adding `GraalVM` feature is only necessary when using Maven. With Gradle the plugin takes care of everything.

2021-05-10 07:22 UTC, ilopmar commented on starter-core/src/test/groovy/io/micronaut/starter/feature/function/awslambda/AwsLambdaSpec.groovy
> +    void 'Application file is not generated for a default application type with gradle and features aws-lambda and graalvm for language: #language'(Language language, String extension) {
Why this change of behaviour?

2021-05-11 09:08 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/function/awslambda/AwsLambda.java
> +        if (featureContext.isPresent(GraalVM.class)) {
No, it does not. Use: 

Application Type:  Serverless function
Features: `aws-lambda`, `graalvm`

and: 

```
% ./gradlew buildNativeLambda

FAILURE: Build failed with an exception.

* What went wrong:
Task 'buildNativeLambda' not found in root project 'micronautguide'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 568ms
```

2021-05-11 09:08 UTC, sdelamo commented on starter-core/src/test/groovy/io/micronaut/starter/feature/function/awslambda/AwsLambdaSpec.groovy
> +    void 'Application file is not generated for a default application type with gradle and features aws-lambda and graalvm for language: #language'(Language language, String extension) {
See above

2021-05-11 09:55 UTC, ilopmar commented on starter-core/src/main/java/io/micronaut/starter/feature/function/awslambda/AwsLambda.java
> +        if (featureContext.isPresent(GraalVM.class)) {
Try with `./gradlew buildNativeLambda -Pmicronaut.runtime=lambda`

2021-05-12 11:18 UTC, graemerocher commented on starter-core/src/main/java/io/micronaut/starter/feature/function/awslambda/AwsLambda.java
> +        if (featureContext.isPresent(GraalVM.class)) {
Yeah this shouldn't be necessary

2021-05-12 11:19 UTC, graemerocher commented on starter-core/src/main/java/io/micronaut/starter/feature/function/awslambda/AwsLambda.java
> +        if (featureContext.isPresent(GraalVM.class)) {
It seems it should only be added if application type is server less function. Note generally

2021-05-17 16:11 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/function/awslambda/AwsLambda.java
> +        if (featureContext.isPresent(GraalVM.class)) {
This does not work either: 

```
./gradlew buildNativeLambda -Pmicronaut.runtime=lambda
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Task 'buildNativeLambda' not found in root project 'micronautguide'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
```

2021-05-17 16:25 UTC, sdelamo commented on starter-core/src/main/java/io/micronaut/starter/feature/function/awslambda/AwsLambda.java
> +        if (featureContext.isPresent(GraalVM.class)) {
@graemerocher > It seems it should only be added if application type is server less function. Not generally.

I did that change.

2021-05-19 04:30 UTC, merged