Create ATP feature (#737)
micronaut-projects/micronaut-starter pull request #856
Opened 2021-07-19 06:13 UTC by yawkat

This PR adds an ATP feature similar to [the guide](https://guides.micronaut.io/latest/micronaut-oracle-autonomous-db-gradle-java.html). 

The commit also adds a default empty config for the new ATP feature and the oracle cloud feature. I put the new config into the main application.yml instead of a separate application-oraclecloud.yml so that it's used out-of-the-box and doesn't lead to confusion for users unfamiliar with micronaut environments.

2021-07-19 07:04 UTC, yawkat commented
format violations \o/

2021-07-19 08:40 UTC, graemerocher approved these changes

2021-07-19 13:23 UTC, burtbeckwith commented
@yawkat this is great, thanks. No need to fork to your own account though, you can just create a branch here

2021-07-19 13:25 UTC, graemerocher commented
don't think we have setup permissions yet

2021-07-25 09:09 UTC, graemerocher requested changes
Sorry picked up a few things on second review, can you address the feedback. Thanks.

2021-07-25 09:09 UTC, graemerocher commented on starter-core/src/main/java/io/micronaut/starter/feature/atp/Atp.java
> +        return "atp";
Rename to `oracle-cloud-atp`

2021-07-25 09:09 UTC, graemerocher commented on starter-core/src/main/java/io/micronaut/starter/feature/atp/Atp.java
> +        return "Provides integration with Oracle Cloud ATP";
Change "ATP" to "Autonomous Database" since this is a full description

2021-07-25 09:09 UTC, graemerocher commented on starter-core/src/main/java/io/micronaut/starter/feature/atp/Atp.java
> +public class Atp implements Feature {
Can you override these methods to provide links to docs:

```
     *
     * @return Returns a link to Micronaut documentation about the feature. eg. https://micronaut-projects.github.io/micronaut-cache/latest/guide/index.html#hazelcast
     */
    @Nullable
    default String getMicronautDocumentation() {
        return null;
    }

    /**
     *
     * @return Returns a link to third party. E.g. https://hazelcast.org
     */
    @Nullable
    default String getThirdPartyDocumentation() {
        return null;
    }
```

2021-07-26 07:32 UTC, yawkat commented
```
  io.micronaut.runtime.exceptions.ApplicationStartupException: Unable to start GRPC server: Failed to bind to address 0.0.0.0/0.0.0.0:47468
  Caused by: java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:47468
  Caused by: java.net.BindException: Address already in use
```

looks like an unrelated intermittent failure, can you rerun the check?

2021-07-26 08:13 UTC, graemerocher commented
yeah it is not related

2021-07-26 08:13 UTC, merged